export default{
    "total_count": 24,
  "incomplete_results": false,
  "items": [
    {
      "login": "paystack",
      "id": 12346441,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjEyMzQ2NDQx",
      "avatar_url": "https://avatars.githubusercontent.com/u/12346441?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paystack",
      "html_url": "https://github.com/paystack",
      "followers_url": "https://api.github.com/users/paystack/followers",
      "following_url": "https://api.github.com/users/paystack/following{/other_user}",
      "gists_url": "https://api.github.com/users/paystack/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paystack/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paystack/subscriptions",
      "organizations_url": "https://api.github.com/users/paystack/orgs",
      "repos_url": "https://api.github.com/users/paystack/repos",
      "events_url": "https://api.github.com/users/paystack/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paystack/received_events",
      "type": "Organization",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "PaystackOSS",
      "id": 62539319,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjYyNTM5MzE5",
      "avatar_url": "https://avatars.githubusercontent.com/u/62539319?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/PaystackOSS",
      "html_url": "https://github.com/PaystackOSS",
      "followers_url": "https://api.github.com/users/PaystackOSS/followers",
      "following_url": "https://api.github.com/users/PaystackOSS/following{/other_user}",
      "gists_url": "https://api.github.com/users/PaystackOSS/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/PaystackOSS/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/PaystackOSS/subscriptions",
      "organizations_url": "https://api.github.com/users/PaystackOSS/orgs",
      "repos_url": "https://api.github.com/users/PaystackOSS/repos",
      "events_url": "https://api.github.com/users/PaystackOSS/events{/privacy}",
      "received_events_url": "https://api.github.com/users/PaystackOSS/received_events",
      "type": "Organization",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "MichaelObi",
      "id": 2924203,
      "node_id": "MDQ6VXNlcjI5MjQyMDM=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2924203?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MichaelObi",
      "html_url": "https://github.com/MichaelObi",
      "followers_url": "https://api.github.com/users/MichaelObi/followers",
      "following_url": "https://api.github.com/users/MichaelObi/following{/other_user}",
      "gists_url": "https://api.github.com/users/MichaelObi/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MichaelObi/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MichaelObi/subscriptions",
      "organizations_url": "https://api.github.com/users/MichaelObi/orgs",
      "repos_url": "https://api.github.com/users/MichaelObi/repos",
      "events_url": "https://api.github.com/users/MichaelObi/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MichaelObi/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "PaystackHQ",
      "id": 14998667,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjE0OTk4NjY3",
      "avatar_url": "https://avatars.githubusercontent.com/u/14998667?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/PaystackHQ",
      "html_url": "https://github.com/PaystackHQ",
      "followers_url": "https://api.github.com/users/PaystackHQ/followers",
      "following_url": "https://api.github.com/users/PaystackHQ/following{/other_user}",
      "gists_url": "https://api.github.com/users/PaystackHQ/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/PaystackHQ/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/PaystackHQ/subscriptions",
      "organizations_url": "https://api.github.com/users/PaystackHQ/orgs",
      "repos_url": "https://api.github.com/users/PaystackHQ/repos",
      "events_url": "https://api.github.com/users/PaystackHQ/events{/privacy}",
      "received_events_url": "https://api.github.com/users/PaystackHQ/received_events",
      "type": "Organization",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "ebuka-paystack",
      "id": 62421715,
      "node_id": "MDQ6VXNlcjYyNDIxNzE1",
      "avatar_url": "https://avatars.githubusercontent.com/u/62421715?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ebuka-paystack",
      "html_url": "https://github.com/ebuka-paystack",
      "followers_url": "https://api.github.com/users/ebuka-paystack/followers",
      "following_url": "https://api.github.com/users/ebuka-paystack/following{/other_user}",
      "gists_url": "https://api.github.com/users/ebuka-paystack/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ebuka-paystack/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ebuka-paystack/subscriptions",
      "organizations_url": "https://api.github.com/users/ebuka-paystack/orgs",
      "repos_url": "https://api.github.com/users/ebuka-paystack/repos",
      "events_url": "https://api.github.com/users/ebuka-paystack/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ebuka-paystack/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "ezra-paystack",
      "id": 51317029,
      "node_id": "MDQ6VXNlcjUxMzE3MDI5",
      "avatar_url": "https://avatars.githubusercontent.com/u/51317029?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ezra-paystack",
      "html_url": "https://github.com/ezra-paystack",
      "followers_url": "https://api.github.com/users/ezra-paystack/followers",
      "following_url": "https://api.github.com/users/ezra-paystack/following{/other_user}",
      "gists_url": "https://api.github.com/users/ezra-paystack/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ezra-paystack/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ezra-paystack/subscriptions",
      "organizations_url": "https://api.github.com/users/ezra-paystack/orgs",
      "repos_url": "https://api.github.com/users/ezra-paystack/repos",
      "events_url": "https://api.github.com/users/ezra-paystack/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ezra-paystack/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    }
}